# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token

          # The following scopes are required:
          #  - public_access (default scope)

          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: JonVojtush
          template: classic
          base: "repositories"
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_languages_recent_days: 365
          plugin_languages_sections: most-used
          plugin_languages_skipped: JonVojtush, Resources
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base, repositories
          plugin_lines_skipped: JonVojtush, Resources
